version: "2"
linters:
  default: standard
  exclusions:
    warn-unused: true
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - path: integrationTests/*
        linters:
          - errcheck
