services:
  goduit-api:
    build:
      context: .
      dockerfile: goduit.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - goduit-queue
    volumes:
      - ./:/app

  goduit-feed-worker:
    build:
      context: .
      dockerfile: goduit-feed-worker.Dockerfile
    depends_on:
      - mongo
      - goduit-queue
    volumes:
      - ./:/app

  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: goduit
      MONGO_INITDB_ROOT_PASSWORD: goduit-password

  goduit-queue:
    image: rabbitmq:4.0.3-management
    container_name: goduit-queue
    ports:
      - 5672:5672
      - 15672:15672
