services:
  goduit-api:
    build:
      context: .
      dockerfile: goduit.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - ./:/app
    environment:
      - QUEUE_TYPE=${QUEUE_TYPE:-rabbitmq}
      - QUEUE_URL=${QUEUE_URL:-amqp://guest:guest@goduit-queue:5672/}

  goduit-feed-worker:
    build:
      context: .
      dockerfile: goduit-feed-worker.Dockerfile
    depends_on:
      - mongo
    volumes:
      - ./:/app
    environment:
      - QUEUE_TYPE=${QUEUE_TYPE:-rabbitmq}
      - QUEUE_URL=${QUEUE_URL:-amqp://guest:guest@goduit-queue:5672/}

  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: goduit
      MONGO_INITDB_ROOT_PASSWORD: goduit-password

  goduit-queue:
    image: rabbitmq:4.0.3-management
    container_name: goduit-queue
    profiles:
      - rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  goduit-redis:
    image: redis:7-alpine
    container_name: goduit-redis
    profiles:
      - redis
    ports:
      - 6379:6379
