version: "3.8"
services:
  web:
    image: acim/go-reflex
    environment:
      - RACE_DETECTOR=1
      - BUILD_ARGS=./cmd/goduit-api/main.go
    container_name: goduit-app
    ports:
      - 9191:9191
    depends_on:
      - mongo
      - mongo-express
    volumes:
      - ./:/app

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: goduit
      MONGO_INITDB_ROOT_PASSWORD: goduit-password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: goduit
      ME_CONFIG_MONGODB_ADMINPASSWORD: goduit-password
      ME_CONFIG_MONGODB_URL: mongodb://goduit:goduit-password@mongo:27017/
