// Code generated by mockery v2.53.2. DO NOT EDIT.

package services

import (
	context "context"

	models "github.com/ravilock/goduit/internal/profileManager/models"
	mock "github.com/stretchr/testify/mock"
)

// mockProfileRegister is an autogenerated mock type for the profileRegister type
type mockProfileRegister struct {
	mock.Mock
}

type mockProfileRegister_Expecter struct {
	mock *mock.Mock
}

func (_m *mockProfileRegister) EXPECT() *mockProfileRegister_Expecter {
	return &mockProfileRegister_Expecter{mock: &_m.Mock}
}

// RegisterUser provides a mock function with given fields: ctx, user
func (_m *mockProfileRegister) RegisterUser(ctx context.Context, user *models.User) (*models.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) (*models.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) *models.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockProfileRegister_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type mockProfileRegister_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *mockProfileRegister_Expecter) RegisterUser(ctx interface{}, user interface{}) *mockProfileRegister_RegisterUser_Call {
	return &mockProfileRegister_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, user)}
}

func (_c *mockProfileRegister_RegisterUser_Call) Run(run func(ctx context.Context, user *models.User)) *mockProfileRegister_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *mockProfileRegister_RegisterUser_Call) Return(_a0 *models.User, _a1 error) *mockProfileRegister_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockProfileRegister_RegisterUser_Call) RunAndReturn(run func(context.Context, *models.User) (*models.User, error)) *mockProfileRegister_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// newMockProfileRegister creates a new instance of mockProfileRegister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockProfileRegister(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockProfileRegister {
	mock := &mockProfileRegister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
