// Code generated by mockery v2.52.2. DO NOT EDIT.

package handlers

import (
	context "context"

	models "github.com/ravilock/goduit/internal/articlePublisher/models"
	mock "github.com/stretchr/testify/mock"
)

// mockArticleLister is an autogenerated mock type for the articleLister type
type mockArticleLister struct {
	mock.Mock
}

type mockArticleLister_Expecter struct {
	mock *mock.Mock
}

func (_m *mockArticleLister) EXPECT() *mockArticleLister_Expecter {
	return &mockArticleLister_Expecter{mock: &_m.Mock}
}

// ListArticles provides a mock function with given fields: ctx, author, tag, limit, offset
func (_m *mockArticleLister) ListArticles(ctx context.Context, author string, tag string, limit int64, offset int64) ([]*models.Article, error) {
	ret := _m.Called(ctx, author, tag, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListArticles")
	}

	var r0 []*models.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) ([]*models.Article, error)); ok {
		return rf(ctx, author, tag, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) []*models.Article); ok {
		r0 = rf(ctx, author, tag, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Article)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, int64) error); ok {
		r1 = rf(ctx, author, tag, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockArticleLister_ListArticles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArticles'
type mockArticleLister_ListArticles_Call struct {
	*mock.Call
}

// ListArticles is a helper method to define mock.On call
//   - ctx context.Context
//   - author string
//   - tag string
//   - limit int64
//   - offset int64
func (_e *mockArticleLister_Expecter) ListArticles(ctx interface{}, author interface{}, tag interface{}, limit interface{}, offset interface{}) *mockArticleLister_ListArticles_Call {
	return &mockArticleLister_ListArticles_Call{Call: _e.mock.On("ListArticles", ctx, author, tag, limit, offset)}
}

func (_c *mockArticleLister_ListArticles_Call) Run(run func(ctx context.Context, author string, tag string, limit int64, offset int64)) *mockArticleLister_ListArticles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64), args[4].(int64))
	})
	return _c
}

func (_c *mockArticleLister_ListArticles_Call) Return(_a0 []*models.Article, _a1 error) *mockArticleLister_ListArticles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockArticleLister_ListArticles_Call) RunAndReturn(run func(context.Context, string, string, int64, int64) ([]*models.Article, error)) *mockArticleLister_ListArticles_Call {
	_c.Call.Return(run)
	return _c
}

// newMockArticleLister creates a new instance of mockArticleLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockArticleLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockArticleLister {
	mock := &mockArticleLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
