// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// articleDeleter is an autogenerated mock type for the articleDeleter type
type articleDeleter struct {
	mock.Mock
}

type articleDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *articleDeleter) EXPECT() *articleDeleter_Expecter {
	return &articleDeleter_Expecter{mock: &_m.Mock}
}

// DeleteArticle provides a mock function with given fields: ctx, slug
func (_m *articleDeleter) DeleteArticle(ctx context.Context, slug string) error {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArticle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// articleDeleter_DeleteArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteArticle'
type articleDeleter_DeleteArticle_Call struct {
	*mock.Call
}

// DeleteArticle is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *articleDeleter_Expecter) DeleteArticle(ctx interface{}, slug interface{}) *articleDeleter_DeleteArticle_Call {
	return &articleDeleter_DeleteArticle_Call{Call: _e.mock.On("DeleteArticle", ctx, slug)}
}

func (_c *articleDeleter_DeleteArticle_Call) Run(run func(ctx context.Context, slug string)) *articleDeleter_DeleteArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *articleDeleter_DeleteArticle_Call) Return(_a0 error) *articleDeleter_DeleteArticle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *articleDeleter_DeleteArticle_Call) RunAndReturn(run func(context.Context, string) error) *articleDeleter_DeleteArticle_Call {
	_c.Call.Return(run)
	return _c
}

// newArticleDeleter creates a new instance of articleDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newArticleDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *articleDeleter {
	mock := &articleDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
