// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/ravilock/goduit/internal/articlePublisher/models"
)

// articleUnpublisher is an autogenerated mock type for the articleUnpublisher type
type articleUnpublisher struct {
	mock.Mock
}

type articleUnpublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *articleUnpublisher) EXPECT() *articleUnpublisher_Expecter {
	return &articleUnpublisher_Expecter{mock: &_m.Mock}
}

// GetArticleBySlug provides a mock function with given fields: ctx, slug
func (_m *articleUnpublisher) GetArticleBySlug(ctx context.Context, slug string) (*models.Article, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetArticleBySlug")
	}

	var r0 *models.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Article, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Article); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Article)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// articleUnpublisher_GetArticleBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArticleBySlug'
type articleUnpublisher_GetArticleBySlug_Call struct {
	*mock.Call
}

// GetArticleBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *articleUnpublisher_Expecter) GetArticleBySlug(ctx interface{}, slug interface{}) *articleUnpublisher_GetArticleBySlug_Call {
	return &articleUnpublisher_GetArticleBySlug_Call{Call: _e.mock.On("GetArticleBySlug", ctx, slug)}
}

func (_c *articleUnpublisher_GetArticleBySlug_Call) Run(run func(ctx context.Context, slug string)) *articleUnpublisher_GetArticleBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *articleUnpublisher_GetArticleBySlug_Call) Return(_a0 *models.Article, _a1 error) *articleUnpublisher_GetArticleBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *articleUnpublisher_GetArticleBySlug_Call) RunAndReturn(run func(context.Context, string) (*models.Article, error)) *articleUnpublisher_GetArticleBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// UnpublishArticle provides a mock function with given fields: ctx, slug
func (_m *articleUnpublisher) UnpublishArticle(ctx context.Context, slug string) error {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for UnpublishArticle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// articleUnpublisher_UnpublishArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpublishArticle'
type articleUnpublisher_UnpublishArticle_Call struct {
	*mock.Call
}

// UnpublishArticle is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *articleUnpublisher_Expecter) UnpublishArticle(ctx interface{}, slug interface{}) *articleUnpublisher_UnpublishArticle_Call {
	return &articleUnpublisher_UnpublishArticle_Call{Call: _e.mock.On("UnpublishArticle", ctx, slug)}
}

func (_c *articleUnpublisher_UnpublishArticle_Call) Run(run func(ctx context.Context, slug string)) *articleUnpublisher_UnpublishArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *articleUnpublisher_UnpublishArticle_Call) Return(_a0 error) *articleUnpublisher_UnpublishArticle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *articleUnpublisher_UnpublishArticle_Call) RunAndReturn(run func(context.Context, string) error) *articleUnpublisher_UnpublishArticle_Call {
	_c.Call.Return(run)
	return _c
}

// newArticleUnpublisher creates a new instance of articleUnpublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newArticleUnpublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *articleUnpublisher {
	mock := &articleUnpublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
