// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/ravilock/goduit/internal/articlePublisher/models"
	mock "github.com/stretchr/testify/mock"
)

// commentGetter is an autogenerated mock type for the commentGetter type
type commentGetter struct {
	mock.Mock
}

type commentGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *commentGetter) EXPECT() *commentGetter_Expecter {
	return &commentGetter_Expecter{mock: &_m.Mock}
}

// GetCommentByID provides a mock function with given fields: ctx, ID
func (_m *commentGetter) GetCommentByID(ctx context.Context, ID string) (*models.Comment, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentByID")
	}

	var r0 *models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Comment, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Comment); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// commentGetter_GetCommentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentByID'
type commentGetter_GetCommentByID_Call struct {
	*mock.Call
}

// GetCommentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *commentGetter_Expecter) GetCommentByID(ctx interface{}, ID interface{}) *commentGetter_GetCommentByID_Call {
	return &commentGetter_GetCommentByID_Call{Call: _e.mock.On("GetCommentByID", ctx, ID)}
}

func (_c *commentGetter_GetCommentByID_Call) Run(run func(ctx context.Context, ID string)) *commentGetter_GetCommentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *commentGetter_GetCommentByID_Call) Return(_a0 *models.Comment, _a1 error) *commentGetter_GetCommentByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *commentGetter_GetCommentByID_Call) RunAndReturn(run func(context.Context, string) (*models.Comment, error)) *commentGetter_GetCommentByID_Call {
	_c.Call.Return(run)
	return _c
}

// newCommentGetter creates a new instance of commentGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newCommentGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *commentGetter {
	mock := &commentGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
