// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/ravilock/goduit/internal/articlePublisher/models"
)

// commentDeleter is an autogenerated mock type for the commentDeleter type
type commentDeleter struct {
	mock.Mock
}

type commentDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *commentDeleter) EXPECT() *commentDeleter_Expecter {
	return &commentDeleter_Expecter{mock: &_m.Mock}
}

// DeleteComment provides a mock function with given fields: ctx, ID
func (_m *commentDeleter) DeleteComment(ctx context.Context, ID string) error {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// commentDeleter_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type commentDeleter_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *commentDeleter_Expecter) DeleteComment(ctx interface{}, ID interface{}) *commentDeleter_DeleteComment_Call {
	return &commentDeleter_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, ID)}
}

func (_c *commentDeleter_DeleteComment_Call) Run(run func(ctx context.Context, ID string)) *commentDeleter_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *commentDeleter_DeleteComment_Call) Return(_a0 error) *commentDeleter_DeleteComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *commentDeleter_DeleteComment_Call) RunAndReturn(run func(context.Context, string) error) *commentDeleter_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentByID provides a mock function with given fields: ctx, ID
func (_m *commentDeleter) GetCommentByID(ctx context.Context, ID string) (*models.Comment, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentByID")
	}

	var r0 *models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Comment, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Comment); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// commentDeleter_GetCommentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentByID'
type commentDeleter_GetCommentByID_Call struct {
	*mock.Call
}

// GetCommentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *commentDeleter_Expecter) GetCommentByID(ctx interface{}, ID interface{}) *commentDeleter_GetCommentByID_Call {
	return &commentDeleter_GetCommentByID_Call{Call: _e.mock.On("GetCommentByID", ctx, ID)}
}

func (_c *commentDeleter_GetCommentByID_Call) Run(run func(ctx context.Context, ID string)) *commentDeleter_GetCommentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *commentDeleter_GetCommentByID_Call) Return(_a0 *models.Comment, _a1 error) *commentDeleter_GetCommentByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *commentDeleter_GetCommentByID_Call) RunAndReturn(run func(context.Context, string) (*models.Comment, error)) *commentDeleter_GetCommentByID_Call {
	_c.Call.Return(run)
	return _c
}

// newCommentDeleter creates a new instance of commentDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newCommentDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *commentDeleter {
	mock := &commentDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
