// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/ravilock/goduit/internal/articlePublisher/models"
)

// commentLister is an autogenerated mock type for the commentLister type
type commentLister struct {
	mock.Mock
}

type commentLister_Expecter struct {
	mock *mock.Mock
}

func (_m *commentLister) EXPECT() *commentLister_Expecter {
	return &commentLister_Expecter{mock: &_m.Mock}
}

// ListComments provides a mock function with given fields: ctx, article
func (_m *commentLister) ListComments(ctx context.Context, article string) ([]*models.Comment, error) {
	ret := _m.Called(ctx, article)

	if len(ret) == 0 {
		panic("no return value specified for ListComments")
	}

	var r0 []*models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.Comment, error)); ok {
		return rf(ctx, article)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.Comment); ok {
		r0 = rf(ctx, article)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, article)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// commentLister_ListComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComments'
type commentLister_ListComments_Call struct {
	*mock.Call
}

// ListComments is a helper method to define mock.On call
//   - ctx context.Context
//   - article string
func (_e *commentLister_Expecter) ListComments(ctx interface{}, article interface{}) *commentLister_ListComments_Call {
	return &commentLister_ListComments_Call{Call: _e.mock.On("ListComments", ctx, article)}
}

func (_c *commentLister_ListComments_Call) Run(run func(ctx context.Context, article string)) *commentLister_ListComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *commentLister_ListComments_Call) Return(_a0 []*models.Comment, _a1 error) *commentLister_ListComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *commentLister_ListComments_Call) RunAndReturn(run func(context.Context, string) ([]*models.Comment, error)) *commentLister_ListComments_Call {
	_c.Call.Return(run)
	return _c
}

// newCommentLister creates a new instance of commentLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newCommentLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *commentLister {
	mock := &commentLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
