// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/ravilock/goduit/internal/articlePublisher/models"
	mock "github.com/stretchr/testify/mock"
)

// commentWriter is an autogenerated mock type for the commentWriter type
type commentWriter struct {
	mock.Mock
}

type commentWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *commentWriter) EXPECT() *commentWriter_Expecter {
	return &commentWriter_Expecter{mock: &_m.Mock}
}

// WriteComment provides a mock function with given fields: ctx, article
func (_m *commentWriter) WriteComment(ctx context.Context, article *models.Comment) error {
	ret := _m.Called(ctx, article)

	if len(ret) == 0 {
		panic("no return value specified for WriteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Comment) error); ok {
		r0 = rf(ctx, article)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// commentWriter_WriteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteComment'
type commentWriter_WriteComment_Call struct {
	*mock.Call
}

// WriteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - article *models.Comment
func (_e *commentWriter_Expecter) WriteComment(ctx interface{}, article interface{}) *commentWriter_WriteComment_Call {
	return &commentWriter_WriteComment_Call{Call: _e.mock.On("WriteComment", ctx, article)}
}

func (_c *commentWriter_WriteComment_Call) Run(run func(ctx context.Context, article *models.Comment)) *commentWriter_WriteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Comment))
	})
	return _c
}

func (_c *commentWriter_WriteComment_Call) Return(_a0 error) *commentWriter_WriteComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *commentWriter_WriteComment_Call) RunAndReturn(run func(context.Context, *models.Comment) error) *commentWriter_WriteComment_Call {
	_c.Call.Return(run)
	return _c
}

// newCommentWriter creates a new instance of commentWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newCommentWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *commentWriter {
	mock := &commentWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
