// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Comparer is an autogenerated mock type for the Comparer type
type Comparer struct {
	mock.Mock
}

type Comparer_Expecter struct {
	mock *mock.Mock
}

func (_m *Comparer) EXPECT() *Comparer_Expecter {
	return &Comparer_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function with given fields: hash, _a1
func (_m *Comparer) Compare(hash string, _a1 string) bool {
	ret := _m.Called(hash, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hash, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Comparer_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type Comparer_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hash string
//   - _a1 string
func (_e *Comparer_Expecter) Compare(hash interface{}, _a1 interface{}) *Comparer_Compare_Call {
	return &Comparer_Compare_Call{Call: _e.mock.On("Compare", hash, _a1)}
}

func (_c *Comparer_Compare_Call) Run(run func(hash string, _a1 string)) *Comparer_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Comparer_Compare_Call) Return(_a0 bool) *Comparer_Compare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Comparer_Compare_Call) RunAndReturn(run func(string, string) bool) *Comparer_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// NewComparer creates a new instance of Comparer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewComparer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Comparer {
	mock := &Comparer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
