// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HasherComparer is an autogenerated mock type for the HasherComparer type
type HasherComparer struct {
	mock.Mock
}

type HasherComparer_Expecter struct {
	mock *mock.Mock
}

func (_m *HasherComparer) EXPECT() *HasherComparer_Expecter {
	return &HasherComparer_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function with given fields: hash, _a1
func (_m *HasherComparer) Compare(hash string, _a1 string) bool {
	ret := _m.Called(hash, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hash, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// HasherComparer_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type HasherComparer_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hash string
//   - _a1 string
func (_e *HasherComparer_Expecter) Compare(hash interface{}, _a1 interface{}) *HasherComparer_Compare_Call {
	return &HasherComparer_Compare_Call{Call: _e.mock.On("Compare", hash, _a1)}
}

func (_c *HasherComparer_Compare_Call) Run(run func(hash string, _a1 string)) *HasherComparer_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *HasherComparer_Compare_Call) Return(_a0 bool) *HasherComparer_Compare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HasherComparer_Compare_Call) RunAndReturn(run func(string, string) bool) *HasherComparer_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function with given fields: _a0
func (_m *HasherComparer) Hash(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasherComparer_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type HasherComparer_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - _a0 string
func (_e *HasherComparer_Expecter) Hash(_a0 interface{}) *HasherComparer_Hash_Call {
	return &HasherComparer_Hash_Call{Call: _e.mock.On("Hash", _a0)}
}

func (_c *HasherComparer_Hash_Call) Run(run func(_a0 string)) *HasherComparer_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *HasherComparer_Hash_Call) Return(_a0 string, _a1 error) *HasherComparer_Hash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HasherComparer_Hash_Call) RunAndReturn(run func(string) (string, error)) *HasherComparer_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewHasherComparer creates a new instance of HasherComparer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasherComparer(t interface {
	mock.TestingT
	Cleanup(func())
}) *HasherComparer {
	mock := &HasherComparer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
