// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// isFollowedChecker is an autogenerated mock type for the isFollowedChecker type
type isFollowedChecker struct {
	mock.Mock
}

type isFollowedChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *isFollowedChecker) EXPECT() *isFollowedChecker_Expecter {
	return &isFollowedChecker_Expecter{mock: &_m.Mock}
}

// IsFollowedBy provides a mock function with given fields: ctx, followed, following
func (_m *isFollowedChecker) IsFollowedBy(ctx context.Context, followed string, following string) bool {
	ret := _m.Called(ctx, followed, following)

	if len(ret) == 0 {
		panic("no return value specified for IsFollowedBy")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, followed, following)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// isFollowedChecker_IsFollowedBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFollowedBy'
type isFollowedChecker_IsFollowedBy_Call struct {
	*mock.Call
}

// IsFollowedBy is a helper method to define mock.On call
//   - ctx context.Context
//   - followed string
//   - following string
func (_e *isFollowedChecker_Expecter) IsFollowedBy(ctx interface{}, followed interface{}, following interface{}) *isFollowedChecker_IsFollowedBy_Call {
	return &isFollowedChecker_IsFollowedBy_Call{Call: _e.mock.On("IsFollowedBy", ctx, followed, following)}
}

func (_c *isFollowedChecker_IsFollowedBy_Call) Run(run func(ctx context.Context, followed string, following string)) *isFollowedChecker_IsFollowedBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *isFollowedChecker_IsFollowedBy_Call) Return(_a0 bool) *isFollowedChecker_IsFollowedBy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *isFollowedChecker_IsFollowedBy_Call) RunAndReturn(run func(context.Context, string, string) bool) *isFollowedChecker_IsFollowedBy_Call {
	_c.Call.Return(run)
	return _c
}

// newIsFollowedChecker creates a new instance of isFollowedChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsFollowedChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *isFollowedChecker {
	mock := &isFollowedChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
