// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/ravilock/goduit/internal/profileManager/models"
)

// ProfileRegister is an autogenerated mock type for the ProfileRegister type
type ProfileRegister struct {
	mock.Mock
}

type ProfileRegister_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfileRegister) EXPECT() *ProfileRegister_Expecter {
	return &ProfileRegister_Expecter{mock: &_m.Mock}
}

// Register provides a mock function with given fields: ctx, model, password
func (_m *ProfileRegister) Register(ctx context.Context, model *models.User, password string) (string, error) {
	ret := _m.Called(ctx, model, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User, string) (string, error)); ok {
		return rf(ctx, model, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.User, string) string); ok {
		r0 = rf(ctx, model, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.User, string) error); ok {
		r1 = rf(ctx, model, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfileRegister_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type ProfileRegister_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - model *models.User
//   - password string
func (_e *ProfileRegister_Expecter) Register(ctx interface{}, model interface{}, password interface{}) *ProfileRegister_Register_Call {
	return &ProfileRegister_Register_Call{Call: _e.mock.On("Register", ctx, model, password)}
}

func (_c *ProfileRegister_Register_Call) Run(run func(ctx context.Context, model *models.User, password string)) *ProfileRegister_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User), args[2].(string))
	})
	return _c
}

func (_c *ProfileRegister_Register_Call) Return(_a0 string, _a1 error) *ProfileRegister_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProfileRegister_Register_Call) RunAndReturn(run func(context.Context, *models.User, string) (string, error)) *ProfileRegister_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewProfileRegister creates a new instance of ProfileRegister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileRegister(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileRegister {
	mock := &ProfileRegister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
