// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/ravilock/goduit/internal/profileManager/models"
	mock "github.com/stretchr/testify/mock"
)

// UserRegister is an autogenerated mock type for the UserRegister type
type UserRegister struct {
	mock.Mock
}

type UserRegister_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRegister) EXPECT() *UserRegister_Expecter {
	return &UserRegister_Expecter{mock: &_m.Mock}
}

// RegisterUser provides a mock function with given fields: ctx, user
func (_m *UserRegister) RegisterUser(ctx context.Context, user *models.User) (*models.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) (*models.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) *models.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRegister_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type UserRegister_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *UserRegister_Expecter) RegisterUser(ctx interface{}, user interface{}) *UserRegister_RegisterUser_Call {
	return &UserRegister_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, user)}
}

func (_c *UserRegister_RegisterUser_Call) Run(run func(ctx context.Context, user *models.User)) *UserRegister_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *UserRegister_RegisterUser_Call) Return(_a0 *models.User, _a1 error) *UserRegister_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRegister_RegisterUser_Call) RunAndReturn(run func(context.Context, *models.User) (*models.User, error)) *UserRegister_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRegister creates a new instance of UserRegister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRegister(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRegister {
	mock := &UserRegister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
