// Code generated by mockery v2.44.1. DO NOT EDIT.

package services

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockUserFollower is an autogenerated mock type for the userFollower type
type mockUserFollower struct {
	mock.Mock
}

type mockUserFollower_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUserFollower) EXPECT() *mockUserFollower_Expecter {
	return &mockUserFollower_Expecter{mock: &_m.Mock}
}

// Follow provides a mock function with given fields: ctx, followed, following
func (_m *mockUserFollower) Follow(ctx context.Context, followed string, following string) error {
	ret := _m.Called(ctx, followed, following)

	if len(ret) == 0 {
		panic("no return value specified for Follow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, followed, following)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockUserFollower_Follow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Follow'
type mockUserFollower_Follow_Call struct {
	*mock.Call
}

// Follow is a helper method to define mock.On call
//   - ctx context.Context
//   - followed string
//   - following string
func (_e *mockUserFollower_Expecter) Follow(ctx interface{}, followed interface{}, following interface{}) *mockUserFollower_Follow_Call {
	return &mockUserFollower_Follow_Call{Call: _e.mock.On("Follow", ctx, followed, following)}
}

func (_c *mockUserFollower_Follow_Call) Run(run func(ctx context.Context, followed string, following string)) *mockUserFollower_Follow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockUserFollower_Follow_Call) Return(_a0 error) *mockUserFollower_Follow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockUserFollower_Follow_Call) RunAndReturn(run func(context.Context, string, string) error) *mockUserFollower_Follow_Call {
	_c.Call.Return(run)
	return _c
}

// newMockUserFollower creates a new instance of mockUserFollower. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUserFollower(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUserFollower {
	mock := &mockUserFollower{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
