// Code generated by mockery v2.44.1. DO NOT EDIT.

package services

import (
	context "context"

	models "github.com/ravilock/goduit/internal/followerCentral/models"
	mock "github.com/stretchr/testify/mock"
)

// mockIsFollowedChecker is an autogenerated mock type for the isFollowedChecker type
type mockIsFollowedChecker struct {
	mock.Mock
}

type mockIsFollowedChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIsFollowedChecker) EXPECT() *mockIsFollowedChecker_Expecter {
	return &mockIsFollowedChecker_Expecter{mock: &_m.Mock}
}

// IsFollowedBy provides a mock function with given fields: ctx, followed, following
func (_m *mockIsFollowedChecker) IsFollowedBy(ctx context.Context, followed string, following string) (*models.Follower, error) {
	ret := _m.Called(ctx, followed, following)

	if len(ret) == 0 {
		panic("no return value specified for IsFollowedBy")
	}

	var r0 *models.Follower
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Follower, error)); ok {
		return rf(ctx, followed, following)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Follower); ok {
		r0 = rf(ctx, followed, following)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Follower)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, followed, following)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIsFollowedChecker_IsFollowedBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFollowedBy'
type mockIsFollowedChecker_IsFollowedBy_Call struct {
	*mock.Call
}

// IsFollowedBy is a helper method to define mock.On call
//   - ctx context.Context
//   - followed string
//   - following string
func (_e *mockIsFollowedChecker_Expecter) IsFollowedBy(ctx interface{}, followed interface{}, following interface{}) *mockIsFollowedChecker_IsFollowedBy_Call {
	return &mockIsFollowedChecker_IsFollowedBy_Call{Call: _e.mock.On("IsFollowedBy", ctx, followed, following)}
}

func (_c *mockIsFollowedChecker_IsFollowedBy_Call) Run(run func(ctx context.Context, followed string, following string)) *mockIsFollowedChecker_IsFollowedBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockIsFollowedChecker_IsFollowedBy_Call) Return(_a0 *models.Follower, _a1 error) *mockIsFollowedChecker_IsFollowedBy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIsFollowedChecker_IsFollowedBy_Call) RunAndReturn(run func(context.Context, string, string) (*models.Follower, error)) *mockIsFollowedChecker_IsFollowedBy_Call {
	_c.Call.Return(run)
	return _c
}

// newMockIsFollowedChecker creates a new instance of mockIsFollowedChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIsFollowedChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIsFollowedChecker {
	mock := &mockIsFollowedChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
