// Code generated by mockery v2.52.2. DO NOT EDIT.

package services

import (
	context "context"

	models "github.com/ravilock/goduit/internal/articlePublisher/models"
	mock "github.com/stretchr/testify/mock"
)

// mockArticlePublisher is an autogenerated mock type for the articlePublisher type
type mockArticlePublisher struct {
	mock.Mock
}

type mockArticlePublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockArticlePublisher) EXPECT() *mockArticlePublisher_Expecter {
	return &mockArticlePublisher_Expecter{mock: &_m.Mock}
}

// PublishArticle provides a mock function with given fields: ctx, article
func (_m *mockArticlePublisher) PublishArticle(ctx context.Context, article *models.Article) error {
	ret := _m.Called(ctx, article)

	if len(ret) == 0 {
		panic("no return value specified for PublishArticle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Article) error); ok {
		r0 = rf(ctx, article)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockArticlePublisher_PublishArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishArticle'
type mockArticlePublisher_PublishArticle_Call struct {
	*mock.Call
}

// PublishArticle is a helper method to define mock.On call
//   - ctx context.Context
//   - article *models.Article
func (_e *mockArticlePublisher_Expecter) PublishArticle(ctx interface{}, article interface{}) *mockArticlePublisher_PublishArticle_Call {
	return &mockArticlePublisher_PublishArticle_Call{Call: _e.mock.On("PublishArticle", ctx, article)}
}

func (_c *mockArticlePublisher_PublishArticle_Call) Run(run func(ctx context.Context, article *models.Article)) *mockArticlePublisher_PublishArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Article))
	})
	return _c
}

func (_c *mockArticlePublisher_PublishArticle_Call) Return(_a0 error) *mockArticlePublisher_PublishArticle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockArticlePublisher_PublishArticle_Call) RunAndReturn(run func(context.Context, *models.Article) error) *mockArticlePublisher_PublishArticle_Call {
	_c.Call.Return(run)
	return _c
}

// newMockArticlePublisher creates a new instance of mockArticlePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockArticlePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockArticlePublisher {
	mock := &mockArticlePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
