// Code generated by mockery v2.44.1. DO NOT EDIT.

package services

import (
	context "context"

	models "github.com/ravilock/goduit/internal/articlePublisher/models"
	mock "github.com/stretchr/testify/mock"
)

// mockArticleGetter is an autogenerated mock type for the articleGetter type
type mockArticleGetter struct {
	mock.Mock
}

type mockArticleGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockArticleGetter) EXPECT() *mockArticleGetter_Expecter {
	return &mockArticleGetter_Expecter{mock: &_m.Mock}
}

// GetArticleBySlug provides a mock function with given fields: ctx, slug
func (_m *mockArticleGetter) GetArticleBySlug(ctx context.Context, slug string) (*models.Article, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetArticleBySlug")
	}

	var r0 *models.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Article, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Article); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Article)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockArticleGetter_GetArticleBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArticleBySlug'
type mockArticleGetter_GetArticleBySlug_Call struct {
	*mock.Call
}

// GetArticleBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *mockArticleGetter_Expecter) GetArticleBySlug(ctx interface{}, slug interface{}) *mockArticleGetter_GetArticleBySlug_Call {
	return &mockArticleGetter_GetArticleBySlug_Call{Call: _e.mock.On("GetArticleBySlug", ctx, slug)}
}

func (_c *mockArticleGetter_GetArticleBySlug_Call) Run(run func(ctx context.Context, slug string)) *mockArticleGetter_GetArticleBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockArticleGetter_GetArticleBySlug_Call) Return(_a0 *models.Article, _a1 error) *mockArticleGetter_GetArticleBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockArticleGetter_GetArticleBySlug_Call) RunAndReturn(run func(context.Context, string) (*models.Article, error)) *mockArticleGetter_GetArticleBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// newMockArticleGetter creates a new instance of mockArticleGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockArticleGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockArticleGetter {
	mock := &mockArticleGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
