// Code generated by mockery v2.52.2. DO NOT EDIT.

package services

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockCommentDeleter is an autogenerated mock type for the commentDeleter type
type mockCommentDeleter struct {
	mock.Mock
}

type mockCommentDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCommentDeleter) EXPECT() *mockCommentDeleter_Expecter {
	return &mockCommentDeleter_Expecter{mock: &_m.Mock}
}

// DeleteComment provides a mock function with given fields: ctx, ID
func (_m *mockCommentDeleter) DeleteComment(ctx context.Context, ID string) error {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockCommentDeleter_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type mockCommentDeleter_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *mockCommentDeleter_Expecter) DeleteComment(ctx interface{}, ID interface{}) *mockCommentDeleter_DeleteComment_Call {
	return &mockCommentDeleter_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, ID)}
}

func (_c *mockCommentDeleter_DeleteComment_Call) Run(run func(ctx context.Context, ID string)) *mockCommentDeleter_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockCommentDeleter_DeleteComment_Call) Return(_a0 error) *mockCommentDeleter_DeleteComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCommentDeleter_DeleteComment_Call) RunAndReturn(run func(context.Context, string) error) *mockCommentDeleter_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCommentDeleter creates a new instance of mockCommentDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCommentDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCommentDeleter {
	mock := &mockCommentDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
