// Code generated by mockery v2.53.2. DO NOT EDIT.

package services

import (
	context "context"

	models "github.com/ravilock/goduit/internal/articlePublisher/models"
	mock "github.com/stretchr/testify/mock"
)

// mockFeedPaginator is an autogenerated mock type for the feedPaginator type
type mockFeedPaginator struct {
	mock.Mock
}

type mockFeedPaginator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFeedPaginator) EXPECT() *mockFeedPaginator_Expecter {
	return &mockFeedPaginator_Expecter{mock: &_m.Mock}
}

// PaginateFeed provides a mock function with given fields: ctx, user, limit, offset
func (_m *mockFeedPaginator) PaginateFeed(ctx context.Context, user string, limit int64, offset int64) ([]models.FeedFragment, error) {
	ret := _m.Called(ctx, user, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for PaginateFeed")
	}

	var r0 []models.FeedFragment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]models.FeedFragment, error)); ok {
		return rf(ctx, user, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []models.FeedFragment); ok {
		r0 = rf(ctx, user, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FeedFragment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(ctx, user, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockFeedPaginator_PaginateFeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PaginateFeed'
type mockFeedPaginator_PaginateFeed_Call struct {
	*mock.Call
}

// PaginateFeed is a helper method to define mock.On call
//   - ctx context.Context
//   - user string
//   - limit int64
//   - offset int64
func (_e *mockFeedPaginator_Expecter) PaginateFeed(ctx interface{}, user interface{}, limit interface{}, offset interface{}) *mockFeedPaginator_PaginateFeed_Call {
	return &mockFeedPaginator_PaginateFeed_Call{Call: _e.mock.On("PaginateFeed", ctx, user, limit, offset)}
}

func (_c *mockFeedPaginator_PaginateFeed_Call) Run(run func(ctx context.Context, user string, limit int64, offset int64)) *mockFeedPaginator_PaginateFeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *mockFeedPaginator_PaginateFeed_Call) Return(_a0 []models.FeedFragment, _a1 error) *mockFeedPaginator_PaginateFeed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockFeedPaginator_PaginateFeed_Call) RunAndReturn(run func(context.Context, string, int64, int64) ([]models.FeedFragment, error)) *mockFeedPaginator_PaginateFeed_Call {
	_c.Call.Return(run)
	return _c
}

// newMockFeedPaginator creates a new instance of mockFeedPaginator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFeedPaginator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFeedPaginator {
	mock := &mockFeedPaginator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
