// Code generated by mockery v2.44.1. DO NOT EDIT.

package services

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockArticleDeleter is an autogenerated mock type for the articleDeleter type
type mockArticleDeleter struct {
	mock.Mock
}

type mockArticleDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockArticleDeleter) EXPECT() *mockArticleDeleter_Expecter {
	return &mockArticleDeleter_Expecter{mock: &_m.Mock}
}

// DeleteArticle provides a mock function with given fields: ctx, slug
func (_m *mockArticleDeleter) DeleteArticle(ctx context.Context, slug string) error {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArticle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockArticleDeleter_DeleteArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteArticle'
type mockArticleDeleter_DeleteArticle_Call struct {
	*mock.Call
}

// DeleteArticle is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *mockArticleDeleter_Expecter) DeleteArticle(ctx interface{}, slug interface{}) *mockArticleDeleter_DeleteArticle_Call {
	return &mockArticleDeleter_DeleteArticle_Call{Call: _e.mock.On("DeleteArticle", ctx, slug)}
}

func (_c *mockArticleDeleter_DeleteArticle_Call) Run(run func(ctx context.Context, slug string)) *mockArticleDeleter_DeleteArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockArticleDeleter_DeleteArticle_Call) Return(_a0 error) *mockArticleDeleter_DeleteArticle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockArticleDeleter_DeleteArticle_Call) RunAndReturn(run func(context.Context, string) error) *mockArticleDeleter_DeleteArticle_Call {
	_c.Call.Return(run)
	return _c
}

// newMockArticleDeleter creates a new instance of mockArticleDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockArticleDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockArticleDeleter {
	mock := &mockArticleDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
