// Code generated by mockery v2.52.2. DO NOT EDIT.

package services

import (
	context "context"

	models "github.com/ravilock/goduit/internal/articlePublisher/models"
	mock "github.com/stretchr/testify/mock"
)

// mockArticleWriter is an autogenerated mock type for the articleWriter type
type mockArticleWriter struct {
	mock.Mock
}

type mockArticleWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockArticleWriter) EXPECT() *mockArticleWriter_Expecter {
	return &mockArticleWriter_Expecter{mock: &_m.Mock}
}

// WriteArticle provides a mock function with given fields: ctx, article
func (_m *mockArticleWriter) WriteArticle(ctx context.Context, article *models.Article) error {
	ret := _m.Called(ctx, article)

	if len(ret) == 0 {
		panic("no return value specified for WriteArticle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Article) error); ok {
		r0 = rf(ctx, article)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockArticleWriter_WriteArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteArticle'
type mockArticleWriter_WriteArticle_Call struct {
	*mock.Call
}

// WriteArticle is a helper method to define mock.On call
//   - ctx context.Context
//   - article *models.Article
func (_e *mockArticleWriter_Expecter) WriteArticle(ctx interface{}, article interface{}) *mockArticleWriter_WriteArticle_Call {
	return &mockArticleWriter_WriteArticle_Call{Call: _e.mock.On("WriteArticle", ctx, article)}
}

func (_c *mockArticleWriter_WriteArticle_Call) Run(run func(ctx context.Context, article *models.Article)) *mockArticleWriter_WriteArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Article))
	})
	return _c
}

func (_c *mockArticleWriter_WriteArticle_Call) Return(_a0 error) *mockArticleWriter_WriteArticle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockArticleWriter_WriteArticle_Call) RunAndReturn(run func(context.Context, *models.Article) error) *mockArticleWriter_WriteArticle_Call {
	_c.Call.Return(run)
	return _c
}

// newMockArticleWriter creates a new instance of mockArticleWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockArticleWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockArticleWriter {
	mock := &mockArticleWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
