// Code generated by mockery v2.44.1. DO NOT EDIT.

package handlers

import (
	context "context"

	models "github.com/ravilock/goduit/internal/profileManager/models"
	mock "github.com/stretchr/testify/mock"
)

// mockProfileGetter is an autogenerated mock type for the profileGetter type
type mockProfileGetter struct {
	mock.Mock
}

type mockProfileGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockProfileGetter) EXPECT() *mockProfileGetter_Expecter {
	return &mockProfileGetter_Expecter{mock: &_m.Mock}
}

// GetProfileByUsername provides a mock function with given fields: ctx, username
func (_m *mockProfileGetter) GetProfileByUsername(ctx context.Context, username string) (*models.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileByUsername")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockProfileGetter_GetProfileByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileByUsername'
type mockProfileGetter_GetProfileByUsername_Call struct {
	*mock.Call
}

// GetProfileByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *mockProfileGetter_Expecter) GetProfileByUsername(ctx interface{}, username interface{}) *mockProfileGetter_GetProfileByUsername_Call {
	return &mockProfileGetter_GetProfileByUsername_Call{Call: _e.mock.On("GetProfileByUsername", ctx, username)}
}

func (_c *mockProfileGetter_GetProfileByUsername_Call) Run(run func(ctx context.Context, username string)) *mockProfileGetter_GetProfileByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockProfileGetter_GetProfileByUsername_Call) Return(_a0 *models.User, _a1 error) *mockProfileGetter_GetProfileByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockProfileGetter_GetProfileByUsername_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *mockProfileGetter_GetProfileByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// newMockProfileGetter creates a new instance of mockProfileGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockProfileGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockProfileGetter {
	mock := &mockProfileGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
