name: Integration Tests
on: [push]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Public a Private Keys
        run: sh scripts/generateJWTRS256Keys.sh
      - name: Start Containers
        run: |
          echo ---Building and starting up docker---
          docker compose up -d
          echo ---Containers up--
      - name: Test Locally With Containers
        run: docker compose exec -T goduit-api go test -count=1 `go list ./... | grep -v integrationTests`
      - name: Test Integration With Containers
        run: docker compose exec -T goduit-api go test ./integrationTests/... -count=1 -p 1

