name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Test Locally
      run: go test -count=1 `go list ./... | grep -v integrationTests`
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Public a Private Keys
        run: sh scripts/generateJWTRS256Keys.sh
      - name: Start Containers
        run: |
          echo ---Building and starting up docker---
          make run
          echo ---Containers up--
      - name: Test Integration With Containers
        run: make test-integration
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
    - name: Checkout
      uses: actions/checkout@v4
    - name: Linting
      uses: golangci/golangci-lint-action@v8
      with:
        version: v1.64.4
        args: --timeout=10m
  govulncheck:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
    - name: Vulnerability Check
      uses: golang/govulncheck-action@v1
